### PR TITLE
Make vimlint a standalone Python script.

### PR DESCRIPTION
**Pull request by lcd047**
I'll just leave this here. :)

### CODE REVIEW

**Comment by dbakker** [comment]
I've been thinking about this a lot, and also what you said [in the discussion at syntastic](https://github.com/scrooloose/syntastic/issues/725#issuecomment-21315893).

I've tried to list the possible advantages and disadvantages of turning Vim-Lint into an autonomous script.

**Advantages of VimLint being installable as a standalone program**
- It would be able to be used easily from the command line (as `vimlint foo.vim`)
- It won't need Vim/Vundle or anything to run except for python and something like `pip` (it would be more complex on Windows though)
- It will make it easier to for syntastic (and possibly other syntax checkers/editors) to make use of it

**Advantages of VimLint being a plugin**
- It can be easily installed using pathogen/Vundle/et cetera which people will already likely have installed
- It will be possible to add documentation explaining different error messages that can be found with `:help` from Vim

**My thoughts**
I'd like many people to use this script. A lot of people do not have time to learn a new tool like `pip`, work out how they can get this to work on Windows or improve their installer script to also install vimlint, so if we go ahead with making VimLint standalone we will probably lose those people.

On the other hand if we keep it as a plugin it will be more annoying to write the necessary code in Syntastic (which is a one time job I'm sure we can overcome), and the tool will be more annoying to use standalone (although I'm guessing probably very few people will want to use it this way).

All in all I think we should make the main goal (linting on the fly and seeing the results) as easy as possible, and that people who want more complex things probably also have the skill set to make it happen. Therefore I believe we should keep it a plugin. Of course, I'm open to more discussion and if a large percentage of people want this change it will happen.

**Comment by lcd047** [comment]
Oh come on, you can install it with a simple `python setup.py install`.  Since there are no C extensions, just pure Python modules, this will work on all systems where Python is installed, and it will copy all files to the right places.  If you want to _also_ support things like pip and easy_install (which would be a good idea in my opinion, since keeping Python modules updated without them is a pain), you can generate a distribution with the same `setup.py`, by running `python setup.py sdist` and friends, (see [the docs](http://docs.python.org/2/distutils/)), and upload the results to [PyPI](https://pypi.python.org/pypi).  That's basically all there is to it, no end user has to _learn_ anything to install your script.  If you want to get fancy you can automate that last stage with [Travis CI](https://travis-ci.org/) and GitHub hooks, and perhaps add [tox](http://tox.readthedocs.org/en/latest/) and [coverage](https://coveralls.io/) tests, but that's just that, getting fancy.

Then again, it's your script.  If you think making a distribution for it would hurt accessibility, so be it.

**Comment by johntyree** [comment]
To dredge up an old discussion, I also vote for the standalone. I can't think of a single Vim user I've ever met that understood what "linting" was and then couldn't figure out how to run `python setup.py install`. I think your imagined user base is just that, imaginary.

On top of that, if this isn't merged somehow into Syntastic, _no-one_ will use it because no one will find it. I found it by looking at Syntastic issues.

**Comment by dbakker** [comment]
> To dredge up an old discussion, I also vote for the standalone. I can't think of a single Vim user I've ever met that understood what "linting" was and then couldn't figure out how to run python setup.py install.

I certainly agree that people could use a standalone, but would it have any advantages (other than the ones I already mentioned) over the more easily installable version?

Another option would be that we merge the `syntax_checkers` directory of this plugin with Syntastic. This way, the maintainers of Syntastic would more easily be able to update it on API changes.

> On top of that, if this isn't merged somehow into Syntastic, no-one will use it because no one will find it. I found it by looking at Syntastic issues.

That's a very interesting idea. Considering that most people using Syntastic will also occasionally edit Vimscript it doesn't seem too much of a stretch that they would like to have built-in linting for it. Another option is that this plugin is simply mentioned in the installation instructions of Syntastic.

**Comment by johntyree** [comment]
YouCompleteMe seems to have no trouble demanding that people go through a much more annoying install process.

Ideally, you'd merge the checker into Syntastic and just register at as a potential checker for vim-script. If the executable is not there, Syntastic won't offer it. Then `pip install vim-lint` would take care of the rest. This requires that you put it on pypi, of course, but puts it at the same level as flake8 and or whatever else.

> Another option is that this plugin is simply mentioned in the installation instructions of Syntastic.

No one reads instructions, unfortunately.

**Comment by dbakker** [comment]
> Ideally, you'd merge the checker into Syntastic and just register at as a potential checker for vim-script. If the executable is not there, Syntastic won't offer it.

In this situation, the executable _is_ there, it's just not included in the standard PATH. Syntastic could use [the same method as this plugin](https://github.com/dbakker/vim-lint/blob/master/syntax_checkers/vim/vimlint.vim) to find the location.

> Then `pip install vim-lint` would take care of the rest. This requires that you put it on pypi, of course, but puts it at the same level as flake8 and or whatever else.

That's true, although having it on pypi would still mean that people would need to install it separately from Syntastic. You're assuming that this person already has `pip` installed, and is willing & capable of installing vim-lint for all users on all the computers (s)he uses Vim on.

Besides that, you have to consider that the main difference with `flake8` and similar linters is that you can assume that the user is already familiar with python and python tools (why else would he be using a python linter). In comparison, vim-lint is only meant to check VimL and as such people might not have any knowledge of the python tools.

I appreciate the fact that your and (@lcd047's) suggestion are architecturally better and will benefit us (the maintainers), but does it translate into any benefit for our users?

**Comment by johntyree** [comment]
A generic user _will_ have `easy_install` at least, if not `pip`. `easy_install vim-lint` is not difficult.

The most obvious benefit is that, like `flake8` and friends, it will work from the command line and can be used in other places (pre-commit hook comes to mind).

I still stand by the notion that anyone who knows what linting is and is smart enough to use vim and syntastic is certainly smart enough to figure out how to automagically install a python package using the standard method.

**Comment by dbakker** [comment]
@johntyree: I just don't see this being a change a lot of people desire, so I think for now I'm keeping this issue closed.

**Comment by myint** [comment]
By the way, standalone and plugin modes are not mutually exclusive. For example, in my fork, I made the standalone install optional. It works as a plugin by default, but I can also make use of `setup.py` if I want to run `vimlint` separately.

**Pull request closed without merging**
